-- AlterTable
ALTER TABLE "Address" ALTER COLUMN "building" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "city" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "province" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "street" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "town" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "zip" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "Ingredient" ALTER COLUMN "name" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "name" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "firstName" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "lastName" SET DATA TYPE VARCHAR(50);
